### ISSUE TITLE
Cannot locate the BeanManager for JavaEE 6

### ISSUE THREAD

**Issue by sesong11** [zkoss/zkbooks#1]
I try to run sample application using java 8 and zk 8.

https://github.com/zkoss/zkbooks/tree/master/developersreference/integration.cdi

and when I open cdiutil.zul it error 

org.zkoss.xel.XelException: Cannot locate the BeanManager for JavaEE 6.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.zkoss.lang.Classes.newInstance(Classes.java:74)
	at org.zkoss.lang.Exceptions.wrap(Exceptions.java:205)

**Comment by hawkchen** [comment]
relate to https://tracker.zkoss.org/browse/ZK-5458

**Comment by KevinLin-potix** [comment]
The fix is now available for testing purposes in the latest FL version ([download](http://www.zkoss.org/download/freshly/)).
If you are using maven/gradle, please update the ZK dependency version to 10.2.0.FL.202504101008-Eval  in your build script (e.g. pom.xml).
Please try it out and let me know if you still encounter any problems while testing.
